### ISSUE TITLE
Feature to allow flagging if a service location information is inactive.

### ISSUE THREAD

**Issue by vijayyadav06** [SCODEMeetup/community-services-locator-ui#30]
We need a way to allow users to flag a location if they find the information is inaccurate or the location is inactive. 

See if we can directly submit a request to SCOS team when a data is flagged as invalid? Is there an email address where we can email programmatically when a dataset is flagged? 
We can aggregate issues on our end and report but automating it completely is preferred.

**Comment by mycarrysun** [comment]
Closing per #42
