### ISSUE TITLE
UI: Update the revised filters in UI

### ISSUE THREAD

**Issue by vijayyadav06** [SCODEMeetup/community-services-locator-ui#39]
Dependent on https://github.com/SCODEMeetup/mofb-api/issues/42

**Comment by mycarrysun** [comment]
See comments [here](https://github.com/SCODEMeetup/mofb-api/issues/42#issuecomment-530492555)

**Comment by mycarrysun** [comment]
I have added a bunch of UI updates with this branch `categories-ui`

Can I get some feedback on this so we can get it merged? 
Thanks!

@vijayyadav06 @mihiramin89 @mollyhenderson

**Comment by mollyhenderson** [comment]
@mycarrysun I like the changes you proposed; can you open a PR?

**Comment by mycarrysun** [comment]
@mollyhenderson Yup! I actually noticed that if you click on one of the categories in the nav bar it doesn't open up the map so I am fixing that first
