### ISSUE TITLE
Pass a limit variable for Agency and Location calls coming from UI

### ISSUE THREAD

**Issue by vijayyadav06** [SCODEMeetup/community-services-locator-ui#40]
We identified that the API is not returning all the data when searched for Services (Agencies and Locations). Currently we limit the results to 500 in API, which is used when no limit query param is passed from UI.

##### AC:
1. Pass a query parameter named "limit" with a long numerical value, say 2000 when making calls to agency and locations 
e.g. `/api/v2/agency?taxonomyId=24&limit=2000`
e.g. `/api/v2/location?taxonomyId=24&agencyId=23560,8500,1610753,1972281,39650,5750620&limit=2000`

**Comment by mihiramin89** [comment]
@vijayyadav06 I think this card has been addressed by https://github.com/SCODEMeetup/community-services-locator-ui/pull/41/files. Can we close this card as addressed?

**Comment by vijayyadav06** [comment]
yes
