### ISSUE TITLE
Cache the API results client-side

### ISSUE THREAD

**Issue by mycarrysun** [SCODEMeetup/community-services-locator-ui#44]
There are a lot of requests to the API if the user is going back and forth between different categories. We should try to store as many things on the client as we can. The locations will not change very often.

This could be part of a PWA feature, using the [Google workbox webpack plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) and choosing the [StaleWhileValidate](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#stale-while-revalidate) caching strategy since these locations will not change very often.

In the meantime, let's just check in `renderer/redux/modules/services/thunks.js` before requesting the API if a value exists in the state already.

**Comment by vijayyadav06** [comment]
Agreed with checking the Redux state first before calling the api for the categories. Although we only have services (aka filters/taxonomies) in redux. are you advising we can benefit by adding Agencies and Locations? thought they are dependent on what filter (of services) you select.

learned something new Google workbox! thanks

**Comment by mycarrysun** [comment]
If we keep the response size low (so it doesn't load up the cache too quickly), I think it is reasonable to try and keep as many locations as we can client side. Because it takes about 3-5 seconds to load depending on which category you choose. You would have immediate locations instead and it would make the app feel a lot more snappy.

**Comment by mycarrysun** [comment]
This change is in #48
